# Generated by Django 2.2 on 2020-12-21 10:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.CharField(max_length=300)),
                ('reviews', models.BigIntegerField(blank=True, null=True)),
                ('likes', models.DecimalField(decimal_places=1, max_digits=6)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TripAdvisorOutlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('cuisines', models.CharField(max_length=300)),
                ('features', models.TextField(max_length=900)),
                ('id_outlet', models.TextField(max_length=600)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('menu', models.TextField(max_length=600)),
                ('name', models.CharField(max_length=300)),
                ('opening_hours', models.TimeField()),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True)),
                ('price_level', models.CharField(max_length=300)),
                ('price_range', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('region', models.CharField(max_length=300)),
                ('reviews_nr', models.DecimalField(decimal_places=1, max_digits=8)),
                ('special_diets', models.CharField(max_length=300)),
                ('street', models.TextField(max_length=800)),
                ('tags', models.TextField(max_length=800)),
                ('url', models.TextField(max_length=800)),
                ('website', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='UberEatsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_outlet', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('brand', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=6, max_digits=6)),
                ('volume', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UberEatsOutlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_outlet', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.CharField(max_length=300)),
                ('reviews_nr', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripAdvisorReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('body', models.TextField(max_length=800)),
                ('traveler_type', models.CharField(blank=True, choices=[('Business', 'Business'), ('Family', 'Family'), ('Friends', 'Friends'), ('Couples', 'Couples'), ('Solo', 'Solo')], max_length=30, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('url', models.TextField(max_length=800)),
                ('id_outlet', models.TextField(max_length=600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripadvisor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
