# Generated by Django 2.2 on 2020-12-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201221_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
    ]
