# Generated by Django 2.2 on 2020-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201221_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='cuisines',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='features',
            field=models.TextField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='id_outlet',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='menu',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='opening_hours',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='price_level',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='price_range',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='region',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='reviews_nr',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='special_diets',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='street',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='tags',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='url',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='website',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisorreviews',
            name='body',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisorreviews',
            name='id_outlet',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisorreviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisorreviews',
            name='url',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='ubereatsmenu',
            name='brand',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ubereatsmenu',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ubereatsmenu',
            name='volume',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ubereatsoutlet',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
