# Generated by Django 2.2 on 2020-12-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201221_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='latitude',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='longitude',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='rating',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='reviews_nr',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
