# Generated by Django 2.2 on 2020-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201221_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='opening_hours',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
