# Generated by Django 2.2 on 2020-12-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201221_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='address',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='country',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='cuisines',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='latitude',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='longitude',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='name',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='opening_hours',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='phone',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='postal_code',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='price_level',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='price_range',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='rating',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='region',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='reviews_nr',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tripadvisoroutlet',
            name='special_diets',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
