# Generated by Django 2.2 on 2020-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201221_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubereatsmenu',
            name='id_outlet',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ubereatsmenu',
            name='price',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
